// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFk2Q_3iSzOoOT9OZnxQ1WNUpM-Dc4vGg',
    appId: '1:394795532317:web:7a8e58c82f06ca0c5d86f4',
    messagingSenderId: '394795532317',
    projectId: 'reddit-clone-tutorial-a354c',
    authDomain: 'reddit-clone-tutorial-a354c.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-a354c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH3S8T4uDwh4Cw5Hxgg3dorW99oZLL4ss',
    appId: '1:394795532317:android:4139cc623ff176eb5d86f4',
    messagingSenderId: '394795532317',
    projectId: 'reddit-clone-tutorial-a354c',
    storageBucket: 'reddit-clone-tutorial-a354c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC5yBTDhA9lu8jTG6jA64QfjkgsYLEPy8',
    appId: '1:394795532317:ios:30a88c508abffa8e5d86f4',
    messagingSenderId: '394795532317',
    projectId: 'reddit-clone-tutorial-a354c',
    storageBucket: 'reddit-clone-tutorial-a354c.appspot.com',
    iosClientId:
        '394795532317-ll3b67437qd7m04i5ps2f3kh9jh8blol.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
